### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ivleth** [voidlabs/elycharts#50]
I like this library, but it was updated a long time ago. Before implementing it, does it work with latest jquery 3.2.1 and raphael.js 2.2.1 ?

Regards

**Comment by bago** [comment]
I simply opened the first example from http://elycharts.com/gallery and updated the 2 dependencies to the latest versions and it seems to work fine:
http://jsfiddle.net/JehdF/1283/

**Comment by ivleth** [comment]
thanks
